config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :reviews
  #Stefani
  ##new, #create, ##edit, #update, ##delete
  
  resources :users #Isaac
  ##new #create ##index ##show ##edit #update ##delete /-/-/ ##login
  
  resources :screenplays, only: [:index, :show] 
  #Auz
  ##index, ##show

  post '/screenplays', to: 'screenplays#filter', as: 'screenplays_filter'

  put 'reviews/:id/like', to: 'reviews#like', as: 'like'

  get '/signup', to: 'users#new', as: 'signup'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/reviews/:id/delete', to: 'reviews#delete', as: 'delete'
  get '/users/:id/delete', to: 'users#delete', as: 'delete_account'

  root 'application#homepage'
  ##homepage of a user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :reviews
    has_many :screenplays, through: :reviews
    # user.likes is the number of likes a user has left on reviews
    has_many :likes
    # user.review_likes is the number of likes a user has received on the reviews they've written
    has_many :review_likes, through: :reviews, source: :likes

    validates_presence_of :name, :username
    validates_presence_of :password, :password_confirmation, on: :new
    validates_uniqueness_of :username
    

    def most_popular_review
        reviews.max do |a, b|
            a.likes.count <=> b.likes.count
        end
    end

    def reviews_count
        self.reviews.count
    end

    def shorter_bio
      if self.bio
        short_bio = self.bio.split(' ')
        short_bio.take(7).join(' ')
      end 
    end
    
    # def likes_count
    #     review.likes.count
    # end

    def user_badge
      if self.review_likes.count <= 9
        "Newbie"
      elsif self.review_likes.count > 9 && self.review_likes.count <= 19
        "Film Critic"
      elsif self.review_likes.count > 19
        "Uber Fan Girl Magnet"
      end 
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update]
  before_action :authorized, only: [:index, :show, :edit, :update, :delete]

  
    def index
        @users = User.all
    end

    def show
      @review = Review.new
    end

    def new
      @user = User.new
    end 

    def create
      @user = User.new(user_params)

      if @user.valid?
        @user.save
        session[:user_id] = @user.id
        redirect_to @user
      else 
        render :new
      end
    end 

    def edit
      if @current_user != @user
        redirect_to @user
      end
    end 

    def update
      if @user.update_attributes(user_params(:name, :username, :bio, :age, :location))
        @user.save
        redirect_to @user
      else 
        render :edit
      end 
    end 

    def delete
      find_user
      @user.destroy
      @user.reviews.destroy_all
      @user.review_likes.destroy_all

      redirect_to signup_path
    end

    private

    def find_user
      @user = User.find(params[:id])
    end 

    def user_params(*args)
      params.require(:user).permit(:name, :username, :bio, :age, :location, :password, :password_confirmation)
    end 
end

app/views/users/_form_review.html.erb
<div class="ui centered grid">
  <div class="session_items_holder">
    <% if review.errors.any? %>
      <div class="ui error message">
        <div class="header">
          Your review couldn't be saved:
        </div>
        <ul class="list">
          <% @review.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="ui inverted large form">
      <%= form_for review do |f| %>
        <div>
          <%= f.label :screenplay_title, "Screenplay:" %>
          <%= f.text_field :screenplay_title, list: "screenplays_autocomplete", onfocus: "this.value=''", value: "#{review.get_screenplay}", :class => "edit_page_session_input" %>
          <datalist id="screenplays_autocomplete">
            <% Screenplay.all.each do |screenplay| %>
              <option value="<%= screenplay.title %>"></option>
            <% end %>
          </datalist>
        </div>
        <div>
          <%= f.label :title, "Review title:" %>
          <%= f.text_field :title, :class => "edit_page_session_input" %>
        </div>
        <div>
          <%= f.label :description, "Review description:" %>
          <%= f.text_area :description, :class => "edit_page_session_input" %>
        </div>
        <div>
          <%= f.label :rating, "Review rating:" %>
          <%= f.select :rating, [1,2,3,4,5], :class => "edit_page_session_input" %>
        </div>
        <div>
          <%= f.submit "Submit Review", :class => 'ui button session_btn' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<p class="center header">Edit your Profile</p>

<div class="ui centered grid">
    <div class="session_items_holder">
        <% if @user.errors.any? %>
            <div class="ui error message">
                <div class="header">
                    Your profile couldn't be saved:
                </div>
                <ul class="list">
                    <% @user.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
        <div class="ui inverted large form">
            <%= form_for @user do |f| %>
                <div>
                    <%= f.label :name %>
                    <%= f.text_field :name, :class => "edit_page_session_input" %>
                </div>
                <div>
                    <%= f.label :username %>
                    <%= f.text_field :username, :class => "edit_page_session_input" %>
                </div>
                <div>
                    <%= f.label :age %>
                    <%= f.number_field :age, :class => "edit_page_session_input", placeholder: "Age" %>
                </div>
                <div>
                    <%= f.label :location, "Country" %>
                    <%= f.text_field :location, :class => "edit_page_session_input", placeholder: 'United States' %>
                </div>
                <div>
                    <%= f.label :bio %>
                    <%= f.text_area :bio, :class => "edit_page_session_input", placeholder: 'Your bio goes here' %>
                </div>
                <div>
                    <%= f.submit "Update Profile", :class => 'ui button session_btn' %>
                </div>
            <% end %>
        </div>
        <button class="ui button delete_button">
            <%= link_to "Delete Account", delete_account_path(@user)%>
        </button>
    </div>
</div>

app/views/users/index.html.erb
<br>
<div class="ui horizontal divider">
  <h2 style="color: white">All Critics</h2>
</div>
<br>
<br>
<div class="ui centered link cards">
    <% @users.each do |user| %>
        <a class="card custom_card" href="<%= user_path(user) %>%">
            <div class="content">
                <div class="center header">
                    <p><%= "#{user.name} | @#{user.username}" %></p>
                </div>
                <div class="center description">
                    <p><%= "#{user.shorter_bio}..." %></p><br><br>
                    <% if user.location %>
                        <p><%= user.location %></p><br>
                        <p><i class="<%= user.location.downcase %> flag"></i></p>
                    <% end %>
                </div>
                
            </div>
            <div class="extra content">
                <i class="newspaper icon"></i>
                <p><%= user.reviews_count %> reviews</p>
            </div>
            <div class="extra content">
                <i class="thumbs up outline icon"></i>
                <p><%= user.review_likes.count %></p>
                <p class="right floated"><%= user.user_badge %></p>
            </div>
        </a>
    <% end %>
</div>

app/views/users/new.html.erb
<div class="session_elements_holder">
  <div class="logo_slogan_holder">
    <img class="ui centered image logo" src="assets/dotwatch-transparent.png">
    <p class="center slogan">Review Your Favorite Film / TV Show</p>
  </div>
  <div class="ui centered grid">
    <div class="session_items_holder">

      <% if @user.errors.any? %>
        <div class="ui error message">
          <div class="header"><%= pluralize(@user.errors.count, "Error") %> prohibited your sign up:</div>
          <ul class="list">
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="ui large form">
        <%= form_for @user do |f| %>
            <div>
              <%= f.text_field :name, class: "session_input", placeholder: "Full Name" %>
            </div>
            <div>
                <%= f.text_field :username, class: "session_input", placeholder: "Username" %>
            </div>
            <div>
                <%= f.password_field :password, class: "session_input", placeholder: "Password" %>
            </div>
            <div>
                <%= f.password_field :password_confirmation, class: "session_input", placeholder: "Confirm Password" %>
            </div>
                <%= f.submit 'Sign Up!', :class => 'ui button session_btn'%>
        <% end %>
        <div>
          <h5>Signed up before? <%= link_to "Log In", login_path %></h5>
        </div>
      </div>
  </div>
</div>
<br>
<br>
<br>

<p class="center bottom_text">Made with ❤️ by bobby_tables.party</p>

app/views/users/show.html.erb
<br>

<div class="ui grid centered card custom_card">
    <div class="content">
        <div class="center header">
            <p><%= @user.name %>'s Profile</p>
        </div>
        <div class="center header">
            <p><%= "@#{@user.username}" %></p>
        </div>
        <div class="center description">
            <% if @user.age %>
                <h4><%= @user.age %> years old</h4><br>
            <% end %>
            <% if @user.location %>
            <p><%= @user.location %></p><br>
            <p><i class="<%= @user.location.downcase %> flag"></i></p><br><br>
            <% end %>
            <p><%= @user.bio %></p>
        </div>
    </div>
    <div class="extra content">
    <div class="left floated">
        <i class="newspaper icon"></i>
        <p><%= @user.reviews_count %> reviews</p>
    </div>
    </div>
    <div class="extra content">
    <div class="left floated">
        <i class="thumbs up outline icon"></i>
        <p><%= @user.review_likes.count %></p>
    </div>
        <p class="right floated"><%= @user.user_badge %></p>
    </div>
    <% if current_user == @user %>
        <div class="ui bottom attached red button">
            <i class="add icon"></i>
            <%= link_to "Edit Profile", edit_user_path(@user) %>
        </div>
    <% end %>
</div>

<br>
<br>
<br>

<% if @user.reviews.length > 0 %>
<div class="ui horizontal divider">
  <% if current_user == @user %>
    <h1 style="color: white">Your Reviews</h1>
  <% else %>
    <h1 style="color: white"><%= @user.username%> Reviews</h1>
  <% end %>
</div>
<% end %>


<% if @user.reviews.length > 0 %>
    <div class="ui centered center link cards">
        <% @user.reviews.each do |review| %>
            <div class="card custom_card">
                <div class="ui image">
                    <%= link_to image_tag(review.screenplay.picture_url), review %>
                </div>
                <div class="content">
                    <div class="header">
                        <%= link_to review.title, review %>
                    </div>
                    <div class="description">
                        <%= link_to review.screenplay.title, screenplay_path(review.screenplay) %>
                    </div>
                </div>
                <div class="extra content">
                    <% review.rating.to_i.times do %>
                    <i class="star icon star_icon"></i>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
<% else %>
    <% if current_user == @user %>
        <div class="ui horizontal divider">
            <h1 style="color: white">Write a Review</h1>
        </div>
        <%= render partial: "form_review", locals: { review: @review } %>
    <% end %>
<% end %>