config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :reviews
  #Stefani
  ##new, #create, ##edit, #update, ##delete
  
  resources :users #Isaac
  ##new #create ##index ##show ##edit #update ##delete /-/-/ ##login
  
  resources :screenplays, only: [:index, :show] 
  #Auz
  ##index, ##show

  post '/screenplays', to: 'screenplays#filter', as: 'screenplays_filter'

  put 'reviews/:id/like', to: 'reviews#like', as: 'like'

  get '/signup', to: 'users#new', as: 'signup'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/reviews/:id/delete', to: 'reviews#delete', as: 'delete'
  get '/users/:id/delete', to: 'users#delete', as: 'delete_account'

  root 'application#homepage'
  ##homepage of a user
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorized
  before_action :find_review, only: [:show, :edit, :update, :like]
  
  def index
    @reviews = Review.all.order("created_at DESC")
  end

  def new
    @review = Review.new
  end

  def show
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.valid?
      @review.save
      flash[:message] = "Review successfully created!"
      flash[:gif] = @review.random_gif
      redirect_to @review
    else
      render :new
    end
  end

  def edit
    if current_user != @review.user
      redirect_to @review
    end
  end

  def update
    if @review.update(review_params)
      redirect_to @review
    else
      render :edit
    end
  end

  def like
    @like = Like.find_by(user_id: session[:user_id], review_id: @review.id)
    if @like
      flash[:like_error] = "You've already liked this review!"
      redirect_to @review
    else #@like.user_id != session[:user_id]
      Like.create(user_id: session[:user_id], review_id: @review.id)
      redirect_to @review
    end 
  end 

  def delete
    find_review
    @review.destroy
    redirect_to reviews_path
  end

  private

  def find_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:title, :description, :rating, :screenplay_title)
  end

end

app/views/reviews/_form.html.erb
<div class="ui centered grid">
  <div class="session_items_holder">
    <% if review.errors.any? %>
      <div class="ui error message">
        <div class="header">
          <p>Your review couldn't be saved:</p>
        </div>
        <ul class="list">
          <% @review.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="ui inverted large form">
      <%= form_for review do |f| %>
        <div>
          <%= f.label :screenplay_title, "Screenplay:" %>
          <%= f.text_field :screenplay_title, list: "screenplays_autocomplete", onfocus: "this.value=''", value: "#{review.get_screenplay}", :class => "edit_page_session_input" %>
          <datalist id="screenplays_autocomplete">
            <% Screenplay.all.each do |screenplay| %>
              <option value="<%= screenplay.title %>"></option>
            <% end %>
          </datalist>
        </div>
        <div>
          <%= f.label :title, "Review title:" %>
          <%= f.text_field :title, :class => "edit_page_session_input" %>
        </div>
        <div>
          <%= f.label :description, "Review description:" %>
          <%= f.text_area :description, :class => "edit_page_session_input" %>
        </div>
        <div>
          <%= f.label :rating, "Review rating:" %>
          <%= f.select :rating, [1,2,3,4,5], :class => "edit_page_session_input" %>
        </div>
        <div>
          <%= f.submit "Submit Review", :class => 'ui button session_btn' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/edit.html.erb
<p class="center header">Edit review</p>


<%= render partial: "form", locals: { review: @review } %>

<div class="ui centered grid">
  <% if current_user == @review.user %>
    <%= link_to "Delete Review", delete_path(@review), class: "ui button delete_button"%>
  <% end %>
</div>

app/views/reviews/index.html.erb
<br>
<div class="ui horizontal divider">
  <h2 style="color: white">All Reviews</h2>
</div>
<br>
<br>
<div class="ui centered link cards">
  <% @reviews.each do |review| %>
    <a class="card custom_card" href="<%= review_path(review) %>">
      <div class="content">
        <div class="center header"><p><%= review.short_title%></p></div>
        <div class="center meta"><p><%= review.get_screenplay %></p></div>
        <div class="center meta"><p><%= review.created_at_to_date %></p></div>
        <div class="center description">
         <p><%= review.short_desc %></p>
        </div>
      </div>
      <div class="extra content">
        <i class="thumbs up outline icon"></i>
        <p><%= review.likes.count %></p>
        <div class="ui right floated content">
          <% review.rating.to_i.times do %>
          <i class="star icon star_icon"></i>
        <% end %>
        </div>
      </div>
    </a>
  <% end %>
</div>

app/views/reviews/new.html.erb
<p class="center header">New review</p>

<%= render partial: "form", locals: { review: @review } %>

app/views/reviews/show.html.erb
<% if flash[:gif] %>
    <div>
      <img class="ui centered large image" src="<%= flash[:gif] %>" style="margin-top: 80px;">
    </div>
<% end %>

<div class="ui centered grid" style="margin-top: 80px;">
<div class="ui centered card review_show_color custom_card">
  <div class="content">
    <div class="center header">
      <h1><%= @review.title %></h1>
    </div>
    <div class="center meta">
      <p>Review by: <%= link_to @review.user.name, user_path(@review.user) %></p>
    </div>
    <div class="center meta">
      <p>Film / TV Show: <%= link_to @review.screenplay.title, screenplay_path(@review.screenplay) %></p><br><br>
    </div>
    <div class="center description">
      <p><%= @review.description %></p><br><br>
    </div>
    <div class="center description">
      <% @review.rating.to_i.times do %>
            <i class="star icon star_icon"></i>
            <% end %>
    </div>
    <div class="ui labeled button left floated" tabindex="0">
      <%= button_to "Like", like_path(@review), method: :put, class: "ui red button center" %>
        <a class="ui basic red left pointing label center">
          <%= @review.likes.count %>
        </a>
      <% if flash[:like_error] %>
        <div class="ui left pointing red basic label">
          <%= flash[:like_error] %>
        </div>
      <% end %>
    </div>
  </div>
  <% if current_user == @review.user %>
        <div class="ui bottom attached red button">
            <i class="add icon"></i>
            <%= link_to "Edit Review", edit_review_path(@review) %>
        </div>
      <% end %>
    </div>
  </div>