config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :reviews
  #Stefani
  ##new, #create, ##edit, #update, ##delete
  
  resources :users #Isaac
  ##new #create ##index ##show ##edit #update ##delete /-/-/ ##login
  
  resources :screenplays, only: [:index, :show] 
  #Auz
  ##index, ##show

  post '/screenplays', to: 'screenplays#filter', as: 'screenplays_filter'

  put 'reviews/:id/like', to: 'reviews#like', as: 'like'

  get '/signup', to: 'users#new', as: 'signup'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/reviews/:id/delete', to: 'reviews#delete', as: 'delete'
  get '/users/:id/delete', to: 'users#delete', as: 'delete_account'

  root 'application#homepage'
  ##homepage of a user
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DotWatch</title>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <script
      src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <% if logged_in? %>
          <div class="ui inverted menu">
            <%= link_to "DotWatch", root_path, class: "active_item item" %>
            <%= link_to "Films / TV Shows", screenplays_path, class: "item general_button_red_h" %>
            <%= link_to "Reviews", reviews_path, class: "item general_button_red_h" %>
            <%= link_to "Critics", users_path, class: "item general_button_red_h" %>
            <div class="right menu">
              <%= link_to "My Profile", user_path(session[:user_id]), class: "item general_button_red_h" %>
              <%= link_to "Logout", logout_path, method: :delete, class: "item general_button_red_h" %>
            </div>
          </div>  
        <% end %>
    <%= yield %>
        <% if logged_in? %>
          <%= link_to '<button type="button" class="new_post_btn" data-tooltip="Write Review"><i class="plus icon"></i></button>'.html_safe, new_review_path %>
        <% end %>
  </body>
</html>